'''

DOCUMENTATION

This is the ClI version of Guess the Number Game. The mechancs of the game is very simple, I have created a list consisting of 10 numbers and then a user gives a give
which is then being verified by the verfication function. Then the user-input number is being verified and checked whether it is equal to the random number generated by
python. If yes then the game is over and asks if you want to retry or quit the game. And if the number isn't the exact as the generated number then the re-match 
function gets activated which gives hints to the player to guess the number. And if the guess gets the correct you win the game and the same retry loop appears again.

'''

import math 
import random

# Importing Important Headers

list = [1, 2, 3, 4, 5, 6, 7 ,8, 9, 10] # creating a list of 10 hnumbers excluding zero
print(list)

# The function which generates the random numbers and takes the player input

def values():
    global guess_number
    global random_number
    guess_number = int(input('Enter any Number in between 10 : '))
    random_number = random.randrange(1, 11)

values()

# Verification function --> Verifying whether the user input was according to game rules.

def verification():

    if guess_number <= 11 and guess_number > 0:
        pass
    else:
        print('Something went wrong ! Try Again')
        exit()

verification()

# Checking if Guess Number == Random Number

def matching():
    if guess_number == random_number:
        print('You Guessed it correct !')
    elif guess_number > random_number:
        print('The number you guessed is smaller than ' + str(guess_number))
    elif guess_number < random_number:
        print('The number you guessed is larger than ' + str(guess_number))
    else:
        pass

matching()

# Re-Matching Counter Loop 

def re_matching():   
    counter = 0 
    while counter == 0:
        values()
        if guess_number != random_number:            
            matching()       
        else:
            print('You Guessed it Correct, Congrats !!')
            counter = counter + 1

re_matching()

# Retry Loop

def retry(): 
    count = 0
    while count == 0:
        retry = str(input('Do you want to play again ? '))
        if retry == 'y' or retry == 'yes' or retry == 'Y':
            values()
            verification()
            matching()
            re_matching()
            retry = str(input('Do you want to play again ? '))
        else:
            print('Come back Again !')
            count = count + 1
            exit()

retry()   



